# Generated by Django 5.2.1 on 2025-05-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiQuetionare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_candidate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_recruiter',
            field=models.BooleanField(default=False),
        ),
    ]
