# Generated by Django 5.2.1 on 2025-05-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiQuetionare', '0002_customuser_is_candidate_customuser_is_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cv',
        ),
        migrations.AddField(
            model_name='candidate',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cv/'),
        ),
    ]
