# Generated by Django 5.2.1 on 2025-05-11 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiQuetionare', '0003_remove_customuser_cv_candidate_cv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='cv',
        ),
    ]
