# Generated by Django 5.2.1 on 2025-05-11 19:55

import AiQuetionare.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AiQuetionare', '0005_jobdescription_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=AiQuetionare.models.unique_file_path),
        ),
    ]
