# Generated by Django 5.2.1 on 2025-05-12 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AiQuetionare', '0006_alter_candidate_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MLModel',
        ),
        migrations.DeleteModel(
            name='QuestionRelationship',
        ),
    ]
